### ISSUE TITLE
github.ref cannot find branch due to fetch-depth, raw bash var captures preceding spacing

### ISSUE THREAD

**Issue by alexiswl** [umccr/v2-samplesheet-maker#17]
Should be

```
      # Checkout code
      - name: Checkout code
        id: git_checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

```
+
```
raw="$( \
            git branch --remotes --contains "${{ github.ref }}" \
          )"
raw="${raw// /}"
echo "branch_name=${raw/origin\/}"
```

Instead
